# Generated by Django 4.2 on 2026-05-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('faculty_advisor', 'Faculty Advisor'), ('medical_verifier', 'Medical Verifier'), ('club_president', 'Club President'), ('club_secretary', 'Club Secretary'), ('club_moderator', 'Club Moderator'), ('camp_coordinator', 'Camp Coordinator'), ('donor', 'Donor'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
